language: java
before_script:
- gpg --import .ossci.gpg.key
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  local-dir: target/generated-docs/
  on:
    branch: master
- provider: script
  script: mvn -s .travis.settings.xml deploy -Prelease
  skip_cleanup: true
  on:
    tags: true
    branch: master
- provider: script
  script: mvn -s .travis.settings.xml deploy -Prelease
  skip_cleanup: true
  on:
    branch: develop
